# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docsdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
