# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teambuildingdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_name', models.CharField(max_length=200)),
                ('go_where', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
