# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_teambuildingdb_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teambuildingdb',
            options={'ordering': ['id'], 'verbose_name': '\u56e2\u5efa\u4fe1\u606f', 'verbose_name_plural': '\u56e2\u5efa\u4fe1\u606f'},
        ),
    ]
