# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20170222_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambuildingdb',
            name='sex',
            field=models.CharField(choices=[('f', '\u5973'), ('m', '\u7537'), ('x', '\u53cc')], default='x', max_length=1),
        ),
    ]
