# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_homepagedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='deleteMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleteMe', models.CharField(max_length=200)),
            ],
        ),
    ]
