# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_deleteme'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteme',
            name='deleteIt',
            field=models.CharField(default=112233, max_length=200),
            preserve_default=False,
        ),
    ]
