# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_deleteme_deleteit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deleteMe',
        ),
    ]
