# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_delete_deleteme'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedb',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
